
name: 'Mobile Tests'
on: 
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      # Push events on master branch
      - main
     

jobs:
  ubuntu-job:
    # Browstack Integration
    name: 'Mo'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout the repository'
        uses: actions/checkout@v2
      # ------- Build ---------------
      - name: 'Build'
        run: npm install   
        
        
      # -------------- Test Components ------------------
      # 1.Test 
      - name: 'test part'
        run: npm run website.automation.test
        if: always()
      - name: Allure EE upload
        if: always()
        continue-on-error: true
        uses: simple-elf/allurectl-action@master
        with:
          allure_results: allure-results
          allure_ee_endpoint: ${{ secrets.ALLURE_EE_ENDPOINT }}
          allure_ee_token: ${{ secrets.ALLURE_EE_TOKEN }}
