
name: 'Mobile Tests'
on: 
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
     
jobs:
  ubuntu-job:
    name: 'Mo'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout the repository'
        uses: actions/checkout@v2
        
      # ------- Build ---------------
      - name: 'Build'
        run: npm install   
        
        
      # -------------- Test Components ------------------
      # 1.Test 
      - name: 'test part'
        run: npm run website.automation.test
        if: always()
 
    # ----------- Allure Report --------------
      
      - uses: actions/checkout@v2
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ./test-results/timeline-report.html
      - uses: actions/download-artifact@v2
        with:
         name: my-artifact
         path: ./test-results/timeline-report.html
    
    
#       - name: Get Allure history
#         uses: actions/checkout@v2
#         if: always()
#         continue-on-error: true
#         with:
#           ref: gh-pages
#           path: gh-pages
#       - name: Allure Report
#         uses: simple-elf/allure-report-action@master
#         if: always()
#         id: allure-report
#         with:
#           allure_results: ./allure-results
#           gh_pages: gh-pages
#           allure_report: allure-report
#           allure_history: allure-history
#           keep_reports: 20
          
#       - name: Deploy report to Github Pages
#         if: always()
#         uses: peaceiris/actions-gh-pages@v2
#         env:
#          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          PUBLISH_BRANCH: gh-pages
#          PUBLISH_DIR: allure-history
