
name: 'Mobile Tests'
on: 
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      # Push events on master branch
      - main
     

jobs:
  ubuntu-job:
    # Browstack Integration
    name: 'Mo'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout the repository'
        uses: actions/checkout@v2
        
      # ------- Build ---------------
      - name: 'Build'
        run: npm install   
        
        
      # -------------- Test Components ------------------
      # 1.Test 
      - name: 'test part'
        run: npm run website.automation.test
        if: always()
      - uses: actions/checkout@v2   
      - uses: ./
        with:
         artifact: test-results
         name: Workflow Report
         path: '*.xml'
         reporter: jest-junit
    
