
name: 'Mobile Tests'
on: 
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      # Push events on master branch
      - main
     

jobs:
  ubuntu-job:
    # Browstack Integration
    name: 'Mo'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout the repository'
        uses: actions/checkout@v2
        
      # ------- Build ---------------
      - name: 'Build'
        run: npm install   
        
        
      # -------------- Test Components ------------------
      # 1.Test 
      - name: 'test part'
        run: npm run website.automation.test
        if: always()
 
    # ----------- Allure Report --------------
      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: ./test-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
         PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         PUBLISH_BRANCH: gh-pages
         PUBLISH_DIR: allure-history
